/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/glb/ccoin.glb 
Author: WhiteTigerArt (https://sketchfab.com/whitetigerart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-coin01-free-trial-8f6db3dcd9774477b63dbf3299ecf5f2
Title: Cartoon Coin01 Free Trial
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ccoin(props) {
  const { nodes, materials } = useGLTF('/glb/ccoin.glb')
  return (
    <group {...props} dispose={null} scale={20}>
      <mesh geometry={nodes.Coin01__0.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/glb/ccoin.glb')
